//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFMIS_BMS.PMS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMS.inventorySoap")]
    public interface inventorySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Inventory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inventory", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> InventoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllEmployeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Office", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Office();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Office", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> OfficeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface inventorySoapChannel : iFMIS_BMS.PMS.inventorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class inventorySoapClient : System.ServiceModel.ClientBase<iFMIS_BMS.PMS.inventorySoap>, iFMIS_BMS.PMS.inventorySoap {
        
        public inventorySoapClient() {
        }
        
        public inventorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public inventorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public inventorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public inventorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Inventory() {
            return base.Channel.Inventory();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> InventoryAsync() {
            return base.Channel.InventoryAsync();
        }
        
        public System.Data.DataTable AllEmployee() {
            return base.Channel.AllEmployee();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllEmployeeAsync() {
            return base.Channel.AllEmployeeAsync();
        }
        
        public System.Data.DataTable Office() {
            return base.Channel.Office();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> OfficeAsync() {
            return base.Channel.OfficeAsync();
        }
    }
}
