//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iFMIS_BMS.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.serviceSoap")]
    public interface serviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PODetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PODetails(string pono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PODetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PODetailsAsync(string pono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable POItems(int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> POItemsAsync(int officeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPAmount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double PPMPAmount(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PPMPAmountAsync(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PPMPItems(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPItems", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PPMPItemsAsync(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPLumpsum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PPMPLumpsum(int year, int officeid, int programid, int accountid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPMPLumpsum", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PPMPLumpsumAsync(int year, int officeid, int programid, int accountid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviceSoapChannel : iFMIS_BMS.ServiceReference1.serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviceSoapClient : System.ServiceModel.ClientBase<iFMIS_BMS.ServiceReference1.serviceSoap>, iFMIS_BMS.ServiceReference1.serviceSoap {
        
        public serviceSoapClient() {
        }
        
        public serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable PODetails(string pono) {
            return base.Channel.PODetails(pono);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PODetailsAsync(string pono) {
            return base.Channel.PODetailsAsync(pono);
        }
        
        public System.Data.DataTable POItems(int officeid) {
            return base.Channel.POItems(officeid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> POItemsAsync(int officeid) {
            return base.Channel.POItemsAsync(officeid);
        }
        
        public double PPMPAmount(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPAmount(year, officeid, programid, accountid);
        }
        
        public System.Threading.Tasks.Task<double> PPMPAmountAsync(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPAmountAsync(year, officeid, programid, accountid);
        }
        
        public System.Data.DataTable PPMPItems(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPItems(year, officeid, programid, accountid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PPMPItemsAsync(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPItemsAsync(year, officeid, programid, accountid);
        }
        
        public System.Data.DataTable PPMPLumpsum(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPLumpsum(year, officeid, programid, accountid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PPMPLumpsumAsync(int year, int officeid, int programid, int accountid) {
            return base.Channel.PPMPLumpsumAsync(year, officeid, programid, accountid);
        }
    }
}
